name: hylove
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  card_swiper: ^2.0.4
  # 列表组件
  grouped_list: ^5.1.2
  # 页面轮播
  expandable_page_view: ^1.0.17
  # 日历
  calendar_timeline: ^1.1.1
  # 点击弹出菜单，四周的好看的样式
#  circular_menu: ^2.0.1
#  hawk_fab_menu: ^1.2.0
  # 一个相当好看的长按弹出菜单的组件
#  pie_menu: ^1.3.0
  # 点击弹出小菜单，悬浮的
  popover: ^0.2.8+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/appIcon/appIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter:
  uses-material-design: true
  assets:
    - asset/login/touxiang.JPG
    - asset/login/bj.JPG
  fonts:
    - family: MyIcons
      fonts:
        - asset: asset/icons/iconfont.ttf
dependency_overrides:
  base_widget:
    path: /Users/hahaha/Desktop/LoveNote/Front/layer_1/base_widget
  hy_get:
    path: /Users/hahaha/Desktop/flutter组件/hy_get