name: hylove
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.2
  card_swiper: ^2.0.4
  # 列表组件
  grouped_list: ^5.1.2
  # 页面轮播
  expandable_page_view: ^1.0.17
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - asset/login/touxiang.JPG
    - asset/login/bj.JPG
  fonts:
    - family: MyIcons
      fonts:
        - asset: asset/icons/iconfont.ttf
dependency_overrides:
  base_widget:
    path: /Users/hahaha/Desktop/LoveNote/Front/layer_1/base_widget